In [25]:
import pandas as pd,scipy,numpy as np
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

,2,2.1,0,3,0.1,0.2,0.3,0.4,1,0.5,0.6,0.7,0.8,0.9,0.10,3.1,2.2,0.11,0.12,0.13,0.14,0.15,0.16,0.17,0.18,0.19,0.20,3.2,0.21,0.22,0.23,1.1,0.24,55,2.3
0,3,3,3,2,1,0,0,0,1,1,1,0,0,1,0,1,2,0,2,2,2,2,2,1,0,0,0,0,0,0,0,1,0,8,1
1,2,1,2,3,1,3,0,3,0,0,0,1,0,0,0,1,2,0,2,0,0,0,0,0,2,0,2,3,2,0,0,2,3,26,3
2,2,2,2,0,0,0,0,0,3,2,0,0,0,3,0,0,2,0,3,2,2,2,2,0,0,3,0,0,0,0,0,3,0,40,1
3,2,3,2,2,2,2,0,2,0,0,0,1,0,0,0,1,2,0,0,0,0,0,0,0,2,2,3,2,3,0,0,2,3,45,3
4,2,3,2,0,0,0,0,0,0,0,0,0,2,1,0,2,2,0,2,0,0,0,1,0,0,0,0,2,0,0,0,1,0,41,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2,1,1,0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,0,25,4
361,3,2,1,0,1,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,1,0,1,0,0,0,2,0,36,4
362,3,2,2,2,3,2,0,2,0,0,0,2,2,0,0,3,3,0,0,0,0,0,0,0,3,0,3,0,3,0,0,2,3,28,3
363,2,1,3,1,2,3,0,2,0,0,0,2,0,0,0,3,2,0,0,0,0,0,0,0,3,0,2,0,1,0,0,2,3,50,3
364,3,2,2,0,0,0,0,0,3,3,0,0,0,1,0,0,2,0,2,3,2,3,0,2,0,2,0,0,0,0,0,3,0,35,1

In [26]:

with open('dermatology.names') as fp:
    cols = []
    for line in fp:
        cols.append(line)

new_list = []
for i in range(len(cols)):
    new_list.append(cols[i].replace('\n', ''))

hash_list = []
for i in range(len(new_list)):
    hash_list.append(new_list[i].split())

var = []
for i in range(len(hash_list)):
    for j in range(len(hash_list[i])):
        if "1:" == hash_list[i][j]:
            var.append(hash_list.index(hash_list[i]))
        if "33:" == hash_list[i][j]:
            var.append(hash_list.index(hash_list[i]))
cl2 = []
for i in range(len(hash_list)):
    for j in range(len(hash_list[i])):
        if "Class:" == hash_list[i][j]:

            cl2.append(hash_list.index(hash_list[i]))

inp={}
for i in cl2:
    inp[str(i)] = hash_list[cl2[0]]

for i in inp.values():
    for j in i:
        if "Class" == j:
            i.clear()
            i.append(j)

inp["112:"]=inp[str(cl2[0])]
del inp[str(cl2[0])]

vari = []
hash_list = hash_list[var[0]:var[-1] + 1]
dict_lst = []

for key, value in inp.items():
    dict_lst.append(key)
    dict_lst.append(value[0])
hash_list.append(dict_lst)

imp = 0
while imp < len(hash_list)-1:
    if len(hash_list[imp]) == 0:
        hash_list.remove(hash_list[imp])
        imp -= 1
    elif not hash_list[imp][0][0].isdigit():
        hash_list.remove(hash_list[imp])
    imp+=1




for i in range(len(hash_list)):
  for j in range(len(hash_list[i])):
    vari+=hash_list[i][j].split(":")

lst = []
index = []
shk = ""


for i in range(len(vari)):
  if vari[i].isdigit():
    index.append(int(vari[i]))
    k = i+1
    while k <= len(vari)-1:
      if not vari[k].isdigit():
        shk += vari[k]
        shk += " "

        k += 1
      else:
        lst.append(shk)
        shk = ""
        break
lst.append(shk)


for i in range(len(lst)):

    for j in range(0, len(lst) - i - 1):
        if index[j] > index[j + 1]:
            temp2 = index[j]
            index[j] = index[j + 1]
            index[j + 1] = temp2
            temp = lst[j]
            lst[j] = lst[j + 1]
            lst[j + 1] = temp
print(lst)

[' erythema ', ' scaling ', ' definite borders ', ' itching ', ' koebner phenomenon ', ' polygonal papules ', ' follicular papules ', ' oral mucosal involvement ', ' knee and elbow involvement ', ' scalp involvement ', ' family history, (0 or 1) ', ' melanin incontinence ', ' eosinophils in the infiltrate ', ' PNL infiltrate ', ' fibrosis of the papillary dermis ', ' exocytosis ', ' acanthosis ', ' hyperkeratosis ', ' parakeratosis ', ' clubbing of the rete ridges ', ' elongation of the rete ridges ', ' thinning of the suprapapillary epidermis ', ' spongiform pustule ', ' munro microabcess ', ' focal hypergranulosis ', ' disappearance of the granular layer ', ' vacuolisation and damage of basal layer ', ' spongiosis ', ' saw-tooth appearance of retes ', ' follicular horn plug ', ' perifollicular parakeratosis ', ' inflammatory monoluclear inflitrate ', ' band-like infiltrate ', ' Age (linear) ', ' Class ']

In [41]:
df = pd.read_csv("dermatology.data")
df = pd.DataFrame(df)
df.columns = lst
df

,erythema,scaling,definite borders,itching,koebner phenomenon,polygonal papules,follicular papules,oral mucosal involvement,knee and elbow involvement,scalp involvement,"family history, (0 or 1)",melanin incontinence,eosinophils in the infiltrate,PNL infiltrate,fibrosis of the papillary dermis,exocytosis,acanthosis,hyperkeratosis,parakeratosis,clubbing of the rete ridges,elongation of the rete ridges,thinning of the suprapapillary epidermis,spongiform pustule,munro microabcess,focal hypergranulosis,disappearance of the granular layer,vacuolisation and damage of basal layer,spongiosis,saw-tooth appearance of retes,follicular horn plug,perifollicular parakeratosis,inflammatory monoluclear inflitrate,band-like infiltrate,Age (linear),Class
0,3,3,3,2,1,0,0,0,1,1,1,0,0,1,0,1,2,0,2,2,2,2,2,1,0,0,0,0,0,0,0,1,0,8,1
1,2,1,2,3,1,3,0,3,0,0,0,1,0,0,0,1,2,0,2,0,0,0,0,0,2,0,2,3,2,0,0,2,3,26,3
2,2,2,2,0,0,0,0,0,3,2,0,0,0,3,0,0,2,0,3,2,2,2,2,0,0,3,0,0,0,0,0,3,0,40,1
3,2,3,2,2,2,2,0,2,0,0,0,1,0,0,0,1,2,0,0,0,0,0,0,0,2,2,3,2,3,0,0,2,3,45,3
4,2,3,2,0,0,0,0,0,0,0,0,0,2,1,0,2,2,0,2,0,0,0,1,0,0,0,0,2,0,0,0,1,0,41,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2,1,1,0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,0,25,4
361,3,2,1,0,1,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,1,0,1,0,0,0,2,0,36,4
362,3,2,2,2,3,2,0,2,0,0,0,2,2,0,0,3,3,0,0,0,0,0,0,0,3,0,3,0,3,0,0,2,3,28,3
363,2,1,3,1,2,3,0,2,0,0,0,2,0,0,0,3,2,0,0,0,0,0,0,0,3,0,2,0,1,0,0,2,3,50,3
364,3,2,2,0,0,0,0,0,3,3,0,0,0,1,0,0,2,0,2,3,2,3,0,2,0,2,0,0,0,0,0,3,0,35,1

In [154]:
dff = df.iloc[:,-2]
lst = []
for i in dff:
  lst.append(i)

for i in range(len(lst)):
  if lst[i] == "?":
    lst[i] = np.nan
n_arr = np.array(lst)
n_arr = n_arr.astype('float64')
n_arr = n_arr.reshape(-1,1)
n_arr

dtype('O')

In [155]:
from sklearn.impute import SimpleImputer
imp1 = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
n_arr = n_arr.reshape(-1,1)
n_arr = imp1.fit_transform(n_arr)
n_arr = n_arr.reshape(-1)
n_arr = n_arr.astype("int")
n_arr

dtype('int64')

In [164]:
df.iloc[:,-2] = n_arr
df

,erythema,scaling,definite borders,itching,koebner phenomenon,polygonal papules,follicular papules,oral mucosal involvement,knee and elbow involvement,scalp involvement,"family history, (0 or 1)",melanin incontinence,eosinophils in the infiltrate,PNL infiltrate,fibrosis of the papillary dermis,exocytosis,acanthosis,hyperkeratosis,parakeratosis,clubbing of the rete ridges,elongation of the rete ridges,thinning of the suprapapillary epidermis,spongiform pustule,munro microabcess,focal hypergranulosis,disappearance of the granular layer,vacuolisation and damage of basal layer,spongiosis,saw-tooth appearance of retes,follicular horn plug,perifollicular parakeratosis,inflammatory monoluclear inflitrate,band-like infiltrate,Age (linear),Class
0,3,3,3,2,1,0,0,0,1,1,1,0,0,1,0,1,2,0,2,2,2,2,2,1,0,0,0,0,0,0,0,1,0,8,1
1,2,1,2,3,1,3,0,3,0,0,0,1,0,0,0,1,2,0,2,0,0,0,0,0,2,0,2,3,2,0,0,2,3,26,3
2,2,2,2,0,0,0,0,0,3,2,0,0,0,3,0,0,2,0,3,2,2,2,2,0,0,3,0,0,0,0,0,3,0,40,1
3,2,3,2,2,2,2,0,2,0,0,0,1,0,0,0,1,2,0,0,0,0,0,0,0,2,2,3,2,3,0,0,2,3,45,3
4,2,3,2,0,0,0,0,0,0,0,0,0,2,1,0,2,2,0,2,0,0,0,1,0,0,0,0,2,0,0,0,1,0,41,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2,1,1,0,1,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2,0,25,4
361,3,2,1,0,1,0,0,0,0,0,0,0,0,0,0,2,2,0,0,0,0,0,0,0,0,1,0,1,0,0,0,2,0,36,4
362,3,2,2,2,3,2,0,2,0,0,0,2,2,0,0,3,3,0,0,0,0,0,0,0,3,0,3,0,3,0,0,2,3,28,3
363,2,1,3,1,2,3,0,2,0,0,0,2,0,0,0,3,2,0,0,0,0,0,0,0,3,0,2,0,1,0,0,2,3,50,3
364,3,2,2,0,0,0,0,0,3,3,0,0,0,1,0,0,2,0,2,3,2,3,0,2,0,2,0,0,0,0,0,3,0,35,1

In [166]:
X = df.iloc[:,:-1]
X
Y = df.iloc[:,-1]
Y

0      1
1      3
2      1
3      3
4      2
      ..
360    4
361    4
362    3
363    3
364    1
Name:  Class , Length: 365, dtype: int64

In [169]:
X_train, X_test, y_train, y_test =  train_test_split(X, Y, test_size=0.2, random_state=42)
X_train_2, X_test_2, y_train_2, y_test_2 =  train_test_split(X, Y, test_size=0.3, random_state=42)
X_train_3, X_test_3, y_train_3, y_test_3 =  train_test_split(X, Y, test_size=0.4, random_state=42)

In [189]:

model = GaussianNB()
model.fit(X_train,y_train)
model2 = GaussianNB()
model2.fit(X_train_2,y_train_2)
model3 = GaussianNB()
model3.fit(X_train_3,y_train_3)

GaussianNB()

In [202]:
model.score(X_test,y_test)
model2.score(X_test_2,y_test_2)
model3.score(X_test_3,y_test_3)
predicted = model.predict(X_test_3)
predicted

array([1, 4, 4, 1, 4, 6, 1, 5, 1, 3, 3, 4, 1, 4, 3, 3, 1, 1, 1, 1, 1, 1,
       5, 3, 3, 3, 4, 1, 1, 4, 6, 1, 2, 5, 2, 5, 4, 3, 6, 4, 1, 4, 2, 5,
       1, 1, 4, 3, 5, 4, 1, 6, 4, 5, 4, 5, 3, 3, 4, 3, 1, 6, 5, 6, 6, 4,
       5, 4, 5, 4, 4, 1, 3, 3, 5, 5, 4, 1, 5, 1, 4, 1, 4, 3, 3, 1, 1, 4,
       3, 3, 4, 1, 4, 5, 5, 5, 1, 3, 4, 1, 4, 4, 1, 5, 4, 4, 2, 4, 1, 1,
       4, 2, 4, 6, 4, 1, 1, 5, 4, 1, 1, 1, 1, 2, 4, 1, 1, 3, 5, 1, 3, 6,
       5, 4, 3, 1, 3, 2, 3, 2, 4, 1, 1, 1, 5, 1])

In [210]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result = confusion_matrix(y_test_3,predicted)

result

array([[45,  0,  0,  0,  0,  0],
       [ 0,  8,  0, 20,  1,  0],
       [ 0,  0, 24,  0,  0,  0],
       [ 0,  0,  0, 18,  0,  0],
       [ 0,  0,  0,  0, 21,  0],
       [ 0,  0,  0,  0,  0,  9]])